### ISSUE TITLE
Long download

### ISSUE THREAD

**Issue by CaramelHeaven** [c-villain/YandexMapsMobile#4]
Я так полагаю, у тебя качаться будет вечность, (40 минут) для spm. Может проще исходники выложить на гит и подтягивать через spm ?) -> https://developer.apple.com/documentation/xcode/adding-package-dependencies-to-your-app

https://github.com/c-villain/YandexMapsMobile/blob/6925ba84e66c1a703744ba27f2bffb987e5caadb/Package.swift#L26

**Comment by c-villain** [comment]
@CaramelHeaven  какие исходники? за ними к Яндексу

в пакете бинарный таргет, собранный на основе xcframework.

**Comment by c-villain** [comment]
@CaramelHeaven Значит смени провайдера

**Comment by CaramelHeaven** [comment]
@c-villain Слишком не профессионально, но мне ожидать ничего не стоит, конечно) Спасибо.
