### ISSUE TITLE
+[YMKMapKit setApiKey:]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by polykuzin** [c-villain/YandexMapsMobile#5]
Стянул к себе либу, Подключил, но ни в какую не хочет заводится. 

Падает на первом же методе setApiKey. Использую версию 4.2.2.

Нашёл инфу, что в пакет нужно добавь настройку линковки: https://github.com/yandex/mapkit-ios-demo/issues/130, нужно ли добавлять что то еще в сам проект?

2023-05-16 18:12:50.224686+0300 [18014:145964] +[YMKMapKit setApiKey:]: unrecognized selector sent to class 0x103c8ec60
2023-05-16 18:12:50.232871+0300 [18014:145964] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[YMKMapKit setApiKey:]: unrecognized selector sent to class 0x103c8ec60'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000180437330 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180051274 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000180445d3c __CFExceptionProem + 0
	3   CoreFoundation                      0x000000018043b224 ___forwarding___ + 1308
	4   CoreFoundation                      0x000000018043d50c _CF_forwarding_prep_0 + 92
	5                              0x0000000102aa54f8 $s811AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtF + 280
	6                              0x0000000102aa6a64 $s811AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtFTo + 196
	7   UIKitCore                           0x00000001126d3ac0 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 292
	8   UIKitCore                           0x00000001126d5008 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 2776
	9   UIKitCore                           0x00000001126d9c08 -[UIApplication _runWithMainScene:transitionContext:completion:] + 856
	10  UIKitCore                           0x0000000111e2e240 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 148
	11  UIKitCore                           0x00000001126d6c7c -[UIApplication _compellApplicationLaunchToCompleteUnconditionally] + 44
	12  UIKitCore                           0x00000001126d6fcc -[UIApplication _run] + 832
	13  UIKitCore                           0x00000001126daf3c UIApplicationMain + 124
	14  libswiftUIKit.dylib                 0x0000000106904454 $s5UIKit17UIApplicationMainys5Int32VAD_SpySpys4Int8VGGSgSSSgAJtF + 100
	15                             0x0000000102aa5380 $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ + 120
	16                             0x0000000102aa52f8 $s811AppDelegateC5$mainyyFZ + 44
	17                             0x0000000102aa6c88 main + 28
	18  dyld                                0x00000001056dd514 start_sim + 20
	19  ???                                 0x00000001057d9f28 0x0 + 4387086120
	20  ???                                 0x0669800000000000 0x0 + 462041174270541824
)
libc++abi: terminating due to uncaught exception of type NSException

**Comment by polykuzin** [comment]
> 

Напрямую в основний проект подключаю

**Comment by c-villain** [comment]
@polykuzin  тогда настройка линковки не нужна

[здесь](https://github.com/c-villain/YandexMapsMobile#recommedations-to-use) смотрел первый пункт?

**Comment by polykuzin** [comment]
@c-villain само собой, подключаю под м1 как надо, в аппделегате тоже всё есть, момент в том, что эта ошибка unrecognized selector sent to class  возникает при любом выдохе метода карт, хотя, например, если ключ не установить он должен выдать что то типо "ApiKey not found".

**Comment by c-villain** [comment]
@polykuzin попробуй [4.3.1](https://github.com/c-villain/YandexMapsMobile/releases/tag/4.3.1)

**Comment by vladimirgoncharov** [comment]
@polykuzin @c-villain Тоже столкнулся с такой проблемой. Помогло только перелинковать в отдельный [пакет](https://github.com/vladimirgoncharov/YandexMapPackageWrapper), используя [пункт 2](https://github.com/c-villain/YandexMapsMobile#recommedations-to-use)

**Comment by c-villain** [comment]
@vladimirgoncharov спасибо за инфу😊🤝

**Comment by yessenali** [comment]
@c-villain @vladimirgoncharov как можно импортнуть только те модули которые нужны из YandexMapsMobile?

**Comment by c-villain** [comment]
@polykuzin сейчас столкнулся с этой же проблемой, помогло прописать в настройках проекта:

<img width="443" alt="Screenshot 2023-12-01 at 18 18 24" src="https://github.com/c-villain/YandexMapsMobile/assets/6235615/3a65fda6-6bd1-4927-a6f6-fece0148af01">
