### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_DCAppAttestService

### ISSUE THREAD

**Issue by hjcn1337** [c-villain/YandexMapsMobile#7]
При сборке с версиями библиотеки 4.6.0 и 4.6.1 выводится ошибка `Undefined symbol: _OBJC_CLASS_$_DCAppAttestService`.
В версии 4.5.2 и ниже сборка проходит успешно. Прошу внести исправления

**Comment by dzhek-space** [comment]
Видимо теперь YandexMapsMobile нужен ещё фреймворк [DeviceCheck](https://developer.apple.com/documentation/devicecheck).
После добавления в _linker flags_ -framework "DeviceCheck", мой проект собрался без ошибок (с версией 4.6.1)

Так же, для подключения YandexMapsMobile как _subdependency_ добавлял строку `.linkedFramework("DeviceCheck")`

**Comment by dzhek-space** [comment]
> При сборке с версиями библиотеки 4.6.0 и 4.6.1 выводится ошибка `Undefined symbol: _OBJC_CLASS_$_DCAppAttestService`. В версии 4.5.2 и ниже сборка проходит успешно. Прошу внести исправления

Видимо теперь YandexMapsMobile нужен ещё фреймворк [DeviceCheck](https://developer.apple.com/documentation/devicecheck).
После добавления в linker flags -framework "DeviceCheck", мой проект собрался без ошибок (с версией 4.6.1)

Так же, для подключения YandexMapsMobile как subdependency добавлял строку .linkedFramework("DeviceCheck")

**Comment by c-villain** [comment]
@dzhek-space спасибо за решение!
