### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by ArthurAvagyan** [c-villain/YandexMapsMobile#8]
MRE: Clean project, installation trough CocoaPods, tried 4.6.1, then 4.6.0, 4.5.0 4.4.0, deleting derived data does not work at all, each time tried clean installation, it just won't work

The following error is received.

error: Sandbox: bash(74976) deny(1) file-write-create /Users/username/Desktop/Projects/projectName/Pods/resources-to-copy-projectName.txt (in target 'projectName' from project 'projectName')
/Users/username/Desktop/Projects/projectName/Pods/Target Support Files/Pods-projectName/Pods-projectName-resources.sh: line 20: /Users/username/Desktop/Projects/projectName/Pods/resources-to-copy-projectName.txt: Operation not permitted
realpath: illegal option -- m
usage: realpath [-q] [path ...]
:20: error: Unexpected failure

also tried to install dependency with SPM, something like 100+ errors were thrown

**Comment by htmlprogrammist** [comment]
How did you handle this problem?

**Comment by ArthurAvagyan** [comment]
I don't really remember at hte moment exactly how i solved it, but  I remember that eventually I realozed I was foing something wrong, and and something g pretty dumb. So if you're facing the same issue try installing step by step, and may be even try a clean installation on an empty project, that might help

**Comment by htmlprogrammist** [comment]
Ok, thank you for your answer

**Comment by ArthurAvagyan** [comment]
Yeah I'm really sorry I can't help at all. One thing to say that was dumb enough issue so i decided just to silently close the issue on github so noone notices😅
