### ISSUE TITLE
Asset validation failed in XCode 15.3+

### ISSUE THREAD

**Issue by tiosdeveloper** [c-villain/YandexMapsMobile#9]
При попытке выложить сборку в AppStoreConnect на версии XCode 15.3 и выше, происходит вот такая ошибка 
<img width="666" alt="Снимок экрана 2024-05-27 в 18 17 40" src="https://github.com/c-villain/YandexMapsMobile/assets/60959275/28bb1596-e9d2-4396-bda6-c09e6d58917a">

**Comment by yadik64** [comment]
Кто-то решил эту проблему?

**Comment by sokolyasnyi** [comment]
+1

**Comment by MZakopailov** [comment]
+1 слежу за обновлениями

**Comment by c-villain** [comment]
Пофикшено в [4.7.0](https://github.com/c-villain/YandexMapsMobile/releases/tag/4.7.0)
